# Generated by Django 2.0.2 on 2020-09-25 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_subcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPublicitario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlBanner', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='API.Categoria'),
        ),
    ]
