# Generated by Django 2.0.2 on 2020-10-05 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_solicitud_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
