# Generated by Django 2.0.2 on 2020-10-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20201005_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
