# Generated by Django 2.0.2 on 2020-10-07 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_solicitud_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('numero_contacto', models.CharField(blank=True, max_length=12, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='API.Solicitud')),
            ],
        ),
    ]
